name: CI
on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

#      - name: instalar paquetes
#        run: |
#          chmod +x script.sh
#          ./script.sh

      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0

      - name: Version Node
        run: node --version
      
      - name: instalar npm
        run: npm install